name: Hassfest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hassfest:
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hassfest
        uses: home-assistant/actions/hassfest@master
